# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addition_colleges.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1680, 791)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget::item{\n"
"    border-bottom:2px solid gray ; \n"
"    border-top: 2px solid gray;\n"
"    border-left: 2px solid gray;\n"
"    border-right: 2px solid gray;\n"
"}\n"
"\n"
"QTableWidget::item::selected{\n"
"    border-bottom:4px solid rgb(0, 170, 0) ; \n"
"    border-top: 4px solid rgb(0, 170, 0);\n"
"    border-left: 4px solid rgb(0, 170, 0);\n"
"    border-right: 4px solid rgb(0, 170, 0);\n"
"}\n"
"QTableWidget::item::selected      \n"
"{\n"
"    color: black;                        \n"
"    background: rgb(170, 255, 0);  \n"
"}\n"
"\n"
"")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(600)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(47)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 2)
        self.pushButton_okey_dia = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton_okey_dia.setFont(font)
        self.pushButton_okey_dia.setObjectName("pushButton_okey_dia")
        self.gridLayout.addWidget(self.pushButton_okey_dia, 1, 0, 1, 1)
        self.pushButton_cancel_dia = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton_cancel_dia.setFont(font)
        self.pushButton_cancel_dia.setObjectName("pushButton_cancel_dia")
        self.gridLayout.addWidget(self.pushButton_cancel_dia, 1, 1, 1, 1)

        # self.retranslateUi(Dialog)


    # def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "新增高校信息"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "新增高校英文名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "高校中文名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "省份"))
        self.pushButton_okey_dia.setText(_translate("Dialog", "确定"))
        self.pushButton_cancel_dia.setText(_translate("Dialog", "取消"))
        QtCore.QMetaObject.connectSlotsByName(Dialog)
