subjectsDict = {
    'AGRICULTURAL SCIENCES': '农业科学',
    'BIOLOGY & BIOCHEMISTRY': '生物与生物化学',
    'CHEMISTRY': '化学',
    'CLINICAL MEDICINE': '临床医学',
    'COMPUTER SCIENCE': '计算机科学',
    'ECONOMICS & BUSINESS': '经济与商学',
    'ENGINEERING': '工程学',
    'ENVIRONMENT/ECOLOGY': '环境生态学',
    'GEOSCIENCES': '地球科学',
    'IMMUNOLOGY': '免疫学',
    'MATERIALS SCIENCE': '材料科学',
    'MATHEMATICS': '数学',
    'MICROBIOLOGY': '微生物学',
    'MOLECULAR BIOLOGY & GENETICS': '分子生物与遗传学',
    'MULTIDISCIPLINARY': '多学科科学',
    'NEUROSCIENCE & BEHAVIOR': '神经科学与行为学',
    'PHARMACOLOGY & TOXICOLOGY': '药学与毒理学',
    'PHYSICS': '物理学',
    'PLANT & ANIMAL SCIENCE': '植物和动物科学',
    'PSYCHIATRY/PSYCHOLOGY': '心理学',
    'SOCIAL SCIENCES, GENERAL': '社会科学总论',
    'SPACE SCIENCE': '空间科学',
}
